### ISSUE TITLE
Embed image generated from PIL using embed() and StringIO

### ISSUE THREAD

**Issue by utsengar** [marrow/mailer#55]
I am trying to generate an image and embed it in an email using [embed](https://github.com/marrow/marrow.mailer/blob/a34130b73b14990457512dabd4eac0250ce016b2/marrow/mailer/message.py#L312)

Get image:

```
    image_buffer = cStringIO.StringIO()
    im.save(image_buffer, "gif")
    imgStr = base64.b64encode(image_buffer.getvalue())
```

Now I use `imgStr` here:

```
   message.embed(filename+'.gif', imgStr)
```

But the image is broken in gmail. 
![screen shot 2015-03-04 at 3 27 51 pm](https://cloud.githubusercontent.com/assets/137799/6495944/3deec816-c283-11e4-83a1-3c3496f4815e.png)

Any suggestions?

**Comment by pjcunningham** [comment]
Just ran into this myself.

You don't need to encode the image - it's done for you by the attach method (which is called by the embed method). This is true whether you pass a file name or data.

Cheers, Paul.
