### ISSUE TITLE
marrow.mailer on pypi

### ISSUE THREAD

**Issue by kalbermattenm** [marrow/mailer#56]
Hi,

This is not an issue, but a question...

Is there any plan to make a new pypi release ?

The last one was done on 2011-11-23 and several bugs where fixed (release 4.0.1, 4.0.2) since then...

Using pip (or easy_install) helps maintaining apps, but I would need some stuff (notably https://github.com/marrow/marrow.mailer/issues/37)...

Sorry for asking questions in the issues...

**Comment by amcgregor** [comment]
Release made.
