### ISSUE TITLE
Bump version to include latest bugfix

### ISSUE THREAD

**Issue by stevenbuccini** [marrow/mailer#73]
I introduced a bug in 4.0.2, which I subsequently fixed in #72. I'm hoping the maintainer can release a new version of this package to resolve this issue.

Thanks!

cc @amcgregor

**Comment by amcgregor** [comment]
Now that my employer has given me sufficient "slack time" to maintain these projects, I'll be releasing a sweep of updates across the `marrow` org. Largely incorporating downstream (work) changes, updating packaging (e.g. use `pyproject.toml`) and modern Python 3 namespacing; Python 2 support is to be dropped.

Closing, though, as [4.0.3](https://pypi.org/project/marrow.mailer/) has been released.
