### ISSUE TITLE
Sendmail transport fails with AttributeError: 'Message' object has no attribute 'sendmail_f'

### ISSUE THREAD

**Issue by pbrackin** [marrow/mailer#76]
See traceback below.  I was able to get it to work using hasattr to gate that if statement.  try/except could also be used.  Maybe a better solution elsewhere tho.  Could not find any other refs to sendmail_f.  I presume y'all were thinking of the "envelop sender" option? Let me know if u want a PR with my patch...

Shutting down transport due to unhandled exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/marrow/mailer/manager/futures.py", line 28, in worker
    result = transport.deliver(message)
  File "/usr/local/lib/python3.4/dist-packages/marrow/mailer/transport/sendmail.py", line 29, in deliver
    if message.sendmail_f:
AttributeError: 'Message' object has no attribute 'sendmail_f'

**Comment by micksp** [comment]
hi @pbrackin did you fix this issue? 
`File "......site-packages/marrow/mailer/transport/sendmail.py", line 29, in deliver
    if message.sendmail_f:
AttributeError: 'Message' object has no attribute 'sendmail_f'
`
